const reportData = [
  {
    "Master-O ID": 101,
    "Content launch date": "2024-11-01",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-05",
    "completed in days": 4,
    "Attempts": 2,
    "score": 80,
    "max score": 100,
    "time spent": "2:30",
    "micro skill name": "Communication",
    "login status": "Logged In",
    "last login date": "2024-11-05"
  },
  {
    "Master-O ID": 102,
    "Content launch date": "2024-11-02",
    "challenges": "active",
    "Completion Status": "Pending",
    "completion date": "2024-11-07",
    "completed in days": 5,
    "Attempts": 3,
    "score": 70,
    "max score": 100,
    "time spent": "3:00",
    "micro skill name": "Leadership",
    "login status": "Logged Out",
    "last login date": "2024-11-07"
  },
  {
    "Master-O ID": 103,
    "Content launch date": "2024-10-30",
    "challenges": "inactive",
    "Completion Status": "Completed",
    "completion date": "2024-11-03",
    "completed in days": 3,
    "Attempts": 1,
    "score": 85,
    "max score": 100,
    "time spent": "1:45",
    "micro skill name": "Collaboration",
    "login status": "Logged In",
    "last login date": "2024-11-03"
  },
  {
    "Master-O ID": 104,
    "Content launch date": "2024-11-01",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-06",
    "completed in days": 5,
    "Attempts": 2,
    "score": 90,
    "max score": 100,
    "time spent": "2:15",
    "micro skill name": "Negotiation",
    "login status": "Logged In",
    "last login date": "2024-11-06"
  },
  {
    "Master-O ID": 105,
    "Content launch date": "2024-11-04",
    "challenges": "inactive",
    "Completion Status": "Pending",
    "completion date": "2024-11-09",
    "completed in days": 5,
    "Attempts": 4,
    "score": 65,
    "max score": 100,
    "time spent": "4:00",
    "micro skill name": "Time Management",
    "login status": "Logged Out",
    "last login date": "2024-11-09"
  },
  {
    "Master-O ID": 106,
    "Content launch date": "2024-11-03",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-05",
    "completed in days": 2,
    "Attempts": 1,
    "score": 95,
    "max score": 100,
    "time spent": "1:30",
    "micro skill name": "Problem Solving",
    "login status": "Logged In",
    "last login date": "2024-11-05"
  },
  {
    "Master-O ID": 107,
    "Content launch date": "2024-11-02",
    "challenges": "inactive",
    "Completion Status": "Failed",
    "completion date": "2024-11-04",
    "completed in days": 2,
    "Attempts": 3,
    "score": 60,
    "max score": 100,
    "time spent": "2:45",
    "micro skill name": "Decision Making",
    "login status": "Logged Out",
    "last login date": "2024-11-04"
  },
  {
    "Master-O ID": 108,
    "Content launch date": "2024-11-01",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-07",
    "completed in days": 6,
    "Attempts": 2,
    "score": 88,
    "max score": 100,
    "time spent": "3:30",
    "micro skill name": "Critical Thinking",
    "login status": "Logged In",
    "last login date": "2024-11-07"
  },
  {
    "Master-O ID": 109,
    "Content launch date": "2024-10-29",
    "challenges": "inactive",
    "Completion Status": "Failed",
    "completion date": "2024-11-01",
    "completed in days": 3,
    "Attempts": 5,
    "score": 40,
    "max score": 100,
    "time spent": "2:10",
    "micro skill name": "Creative Thinking",
    "login status": "Logged Out",
    "last login date": "2024-11-01"
  },
  {
    "Master-O ID": 110,
    "Content launch date": "2024-11-02",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-05",
    "completed in days": 3,
    "Attempts": 2,
    "score": 92,
    "max score": 100,
    "time spent": "1:50",
    "micro skill name": "Teamwork",
    "login status": "Logged In",
    "last login date": "2024-11-05"
  },
  {
    "Master-O ID": 111,
    "Content launch date": "2024-10-31",
    "challenges": "inactive",
    "Completion Status": "Pending",
    "completion date": "2024-11-06",
    "completed in days": 6,
    "Attempts": 4,
    "score": 75,
    "max score": 100,
    "time spent": "4:10",
    "micro skill name": "Communication",
    "login status": "Logged Out",
    "last login date": "2024-11-06"
  },
  {
    "Master-O ID": 112,
    "Content launch date": "2024-11-01",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-08",
    "completed in days": 7,
    "Attempts": 3,
    "score": 85,
    "max score": 100,
    "time spent": "3:20",
    "micro skill name": "Leadership",
    "login status": "Logged In",
    "last login date": "2024-11-08"
  },
  {
    "Master-O ID": 113,
    "Content launch date": "2024-11-03",
    "challenges": "inactive",
    "Completion Status": "Failed",
    "completion date": "2024-11-04",
    "completed in days": 1,
    "Attempts": 1,
    "score": 55,
    "max score": 100,
    "time spent": "1:40",
    "micro skill name": "Collaboration",
    "login status": "Logged Out",
    "last login date": "2024-11-04"
  },
  {
    "Master-O ID": 114,
    "Content launch date": "2024-11-02",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-09",
    "completed in days": 7,
    "Attempts": 2,
    "score": 80,
    "max score": 100,
    "time spent": "2:50",
    "micro skill name": "Negotiation",
    "login status": "Logged In",
    "last login date": "2024-11-09"
  },
  {
    "Master-O ID": 115,
    "Content launch date": "2024-11-04",
    "challenges": "inactive",
    "Completion Status": "Pending",
    "completion date": "2024-11-07",
    "completed in days": 3,
    "Attempts": 4,
    "score": 65,
    "max score": 100,
    "time spent": "3:40",
    "micro skill name": "Time Management",
    "login status": "Logged Out",
    "last login date": "2024-11-07"
  },
  {
    "Master-O ID": 116,
    "Content launch date": "2024-11-05",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-06",
    "completed in days": 1,
    "Attempts": 2,
    "score": 98,
    "max score": 100,
    "time spent": "1:20",
    "micro skill name": "Problem Solving",
    "login status": "Logged In",
    "last login date": "2024-11-06"
  },
  {
    "Master-O ID": 117,
    "Content launch date": "2024-11-01",
    "challenges": "inactive",
    "Completion Status": "Failed",
    "completion date": "2024-11-03",
    "completed in days": 2,
    "Attempts": 5,
    "score": 50,
    "max score": 100,
    "time spent": "2:35",
    "micro skill name": "Decision Making",
    "login status": "Logged Out",
    "last login date": "2024-11-03"
  },
  {
    "Master-O ID": 118,
    "Content launch date": "2024-10-30",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-02",
    "completed in days": 2,
    "Attempts": 3,
    "score": 92,
    "max score": 100,
    "time spent": "1:55",
    "micro skill name": "Critical Thinking",
    "login status": "Logged In",
    "last login date": "2024-11-02"
  },
  {
    "Master-O ID": 119,
    "Content launch date": "2024-11-02",
    "challenges": "inactive",
    "Completion Status": "Pending",
    "completion date": "2024-11-05",
    "completed in days": 3,
    "Attempts": 1,
    "score": 70,
    "max score": 100,
    "time spent": "2:20",
    "micro skill name": "Creative Thinking",
    "login status": "Logged Out",
    "last login date": "2024-11-05"
  },
  {
    "Master-O ID": 120,
    "Content launch date": "2024-10-31",
    "challenges": "active",
    "Completion Status": "Completed",
    "completion date": "2024-11-08",
    "completed in days": 7,
    "Attempts": 2,
    "score": 90,
    "max score": 100,
    "time spent": "3:45",
    "micro skill name": "Teamwork",
    "login status": "Logged In",
    "last login date": "2024-11-08"
  }
];

export default reportData;